name: black-action
on: [pull_request]
jobs:
  black:
    name: runner / black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - uses: BSFishy/pip-action@v1
        with:
          packages: black
      - run: python3 -m black pipeline/
      - uses: reviewdog/action-suggester@v1
        with:
          tool_name: black
